version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: assignment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assignment
    volumes:
      - ./docker/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped
